spring:
  datasource:
    url: jdbc:mysql://localhost/board
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate.format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
